name: pages
run-name: Publishing pages

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          
      - run: curl -fsSL https://get.pnpm.io/install.sh | sh -
      - run: pnpm i
      - run: pnpm run build
      
      - uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: dist
